# Dependencies
plugins:
  - jekyll-feed
  - jekyll-github-metadata
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-timeago
  - jemoji
  
feed:
  excerpt_only: true
  tags:
    except:
      - private
    
# Permalinks
permalink: /:categories/:year/:month/:title/

repository: kraymer/excommito

# Setup
url: http://kray.me

# Set to '' in case of hosting on GitHub pages,
# i.e. `http://<username>.github.io`
baseurl: ''

title: Ex commito

tagline: Kraymer's technical blog

# Markdown enabled, however don't use more than one paragraph (enforced by `>`)
description:         >
  [`@kraymer`{:style="background: rgba(255, 255, 255, 0.15)"}](mailto:kraymer+excommito@gmail.com) recorded thoughts

# The tags listed as entries in the sidebar
sidebar_tags:        [open-source, music-management]

# Fallback image and color if not overwritten for tag or post
image:               /public/img/back.jpg
color:               '#A85641'

# Fonts
font:                '"PT Serif", Georgia, serif'
font_accent:         '"Roboto Slab", "PT Serif", Georgia, serif'
load_google_fonts:   'Roboto+Slab:700|PT+Serif:400,400italic,700,700italic'

# Syntax highlighting
markdown: kramdown
highlighter: rouge

# About yourself
author:
  name:              'Fabrice Laporte'

  # This photo will be used in the about section
  photo:
  photo2x:

  # Markdown enabled, can use multiple paragraphs (enabled by `|`)
  # about:             |
  #  ''

  # Social media icons in sidebar
  # Comment/uncommet to show/hide
  # Icons appear in order, can be rearranged:
  social:
    # vimeo:           _username_
    # vine:            _username_
    # spotify:         user/_number_
    # soundcloud:      _username_
    # instagram:       _username_
    # flickr:          _string_@_string_
    # 500px:           _username_
    # dribbble:        _username_
    # behance:         _username_
    # deviantart:      _username_
    # ello:            _username_
    # twitch:          _username_
    # steam:           _number_
    reddit:          kraymer
    # tumblr:          _username_
    # pinterest:       _username_
    # foursquare:      _number_
    # yelp:            _string_
    github:          kraymer
    stackoverflow:   5181/kraymer
    lichess:        kraymer
    # npm:             _username_
    # hackernews:      _username_
    # trello:          _firstname__lastname_
    # linkedin:        _firstname_-_lastname_-_string_
    # xing:            _firstname___lastname__counter_
    # blogger:         _number_
    # delicious:       _username_
    # stumbleupon:     _username_
    # paypal:          _username_
    cv:               kraymer


kramdown:
  math_engine:       mathjax
  math_engine_opts:
    preview:         true
    preview_as_code: true

compress_html:
  comments:          ["<!-- ", " -->"]
  clippings:         all
  endings:           all
  ignore:
    envs:            [local]

sass:
  style:             compressed

# Defaults
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      dropcaps: true
  - scope:
      path: "_drafts"
    values:
      layout: draft
      draftnote: true
      permalink: /drafts/:title/

collections:
  drafts:
    output: true
    permalink: /:collection/:name
  chess:
    output: true
    permalink: /:collection/:name
  recipes:
    output: false
    permalink: /:collection/:name